# Generated by Django 4.2.5 on 2023-09-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('character_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('people_live', models.IntegerField()),
                ('people_on_gta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(max_length=255)),
                ('streamer_link', models.URLField(unique=True)),
                ('streamer_is_live', models.BooleanField()),
                ('streamer_on_gta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterGangLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(max_length=255)),
                ('member_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.character')),
                ('member_gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.gang')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.streamer'),
        ),
    ]
