# Generated by Django 4.2.5 on 2023-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0002_alter_character_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_link',
            field=models.URLField(),
        ),
    ]
