# Generated by Django 4.2.5 on 2023-09-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0003_alter_character_character_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='streamer_link',
            field=models.URLField(),
        ),
    ]
