# Generated by Django 4.2.5 on 2023-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0004_alter_character_character_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=255),
        ),
    ]
