# Generated by Django 4.2.5 on 2023-09-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0005_alter_character_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gang',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
