# Generated by Django 4.2.5 on 2023-09-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0007_streamer_streamer_title_streamer_streamer_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GangData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_live', models.IntegerField()),
                ('people_on_gta', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directory.gang')),
            ],
        ),
    ]
