# Generated by Django 4.2.5 on 2023-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0008_gangdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
